# Generated by Django 5.2.17 on 2026-09-24 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=80)),
                ('resource', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=40)),
                ('location', models.CharField(choices=[('cloud', '云端'), ('local', '本地')], default='cloud', max_length=10)),
                ('base_url', models.URLField(blank=True)),
                ('endpoints', models.JSONField(blank=True, default=dict)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('credentials', models.TextField(blank=True)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('service_key', models.CharField(default='default', max_length=60)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('path', models.CharField(max_length=1000)),
                ('body_type', models.CharField(choices=[('json', 'JSON'), ('form', 'Form'), ('text', 'Text')], default='json', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='automation.project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('case_ids', models.JSONField(default=list)),
                ('stop_on_failure', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='automation.project')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('http', 'HTTP'), ('pytest', 'Pytest')], default='http', max_length=10)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P1', max_length=2)),
                ('author', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('request_overrides', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=list)),
                ('extract', models.JSONField(blank=True, default=dict)),
                ('node_id', models.CharField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.endpoint')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='automation.project')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('scan_testcase', '扫描 Python 测试用例')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('passed', 'passed'), ('failed', 'failed'), ('error', 'error'), ('cancelled', 'cancelled')], default='queued', max_length=20)),
                ('snapshot', models.TextField()),
                ('total', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('log', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='automation.project')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': [('execute_testrun', '执行测试'), ('cancel_testrun', '取消测试')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('case_id_snapshot', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('duration_ms', models.FloatField(default=0)),
                ('request', models.JSONField(default=dict)),
                ('response', models.JSONField(default=dict)),
                ('assertions', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('log', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='automation.testrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('owner', 'code', 'location'), name='unique_owner_env'),
        ),
    ]
