# Generated by Django 5.2.17 on 2026-09-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='function_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
