# Generated by Django 5.2.17 on 2026-09-24 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_endpoint_function_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('config_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['-id'], 'permissions': [('manage_public_environment', '维护公共环境配置')]},
        ),
        migrations.RemoveConstraint(
            model_name='environment',
            name='unique_owner_env',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='use_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='environment',
            name='scope',
            field=models.CharField(choices=[('public', '公共配置'), ('private', '私有配置')], default='private', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'public')), fields=('code', 'location'), name='unique_public_env'),
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'private')), fields=('owner', 'code', 'location'), name='unique_private_env'),
        ),
        migrations.AddField(
            model_name='environmentsession',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.environment'),
        ),
        migrations.AddField(
            model_name='environmentsession',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='environmentsession',
            constraint=models.UniqueConstraint(fields=('owner', 'environment'), name='unique_environment_session'),
        ),
    ]
